### PR TITLE
Fix 403 error when making calls to Github's API

### PR DESCRIPTION
**Pull request by 9Morello**
I recently tried installing Ceramic in a new computer, and ran into errors. After investigating a bit, seems like Github now requires the 'User-Agent' header to be set for API requests, or they return a 403 error.

This PR fixes the problem by adding this header to the HTTP requests made. I also removed a third-party HTTP library dependency that wasn't really needed (the original code also used Haxe's built-in HTTP functions).

### CODE REVIEW

**Comment by jeremyfa** [comment]
Thanks, I’ll take a look at that next week!

**Comment by jeremyfa** [comment]
After taking a closer look, I'm not against removing akifox http as a dependency, but current alternative in the PR doesn't display http error code + error message like the previous implementation. I'll merge this code if that is also handled in the alternative implementation based on `haxe.Http` but can't merge it as is

**Comment by jeremyfa** [comment]
Added the change myself, can now merge

**Comment by 9Morello** [comment]
@jeremyfa thank you, i got busy with work and only now got to see your reply. Glad it's solved, cheers!

**Pull request merged**
